#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const util = require('util');

const createParser = require('./jparser');
const ErrorManager = require('./ErrorManager');
const ImportManager = require('./ImportManager');

// promisify exec
const execPromise = util.promisify(exec);

if (process.argv.length < 3) {
  console.error('يرجا ئعطائ ملف جني');
  process.exit(1);
}

var mainFilePath = null;
var jinniParams = [];
var userParams = [];

var processArgs = process.argv.slice(2);

// parse parameters
processArgs.forEach(arg => {
	if (arg.startsWith('--') && !mainFilePath) {
		jinniParams.push(arg);
	} else if (!arg.startsWith('--') && !mainFilePath) {
		mainFilePath = path.resolve(arg);
	} else {
		userParams.push(arg);
	}
});

//var mainFilePath = path.resolve(process.argv[2]);
var is_nowarning = jinniParams.includes('--nowarnings') || jinniParams.includes('--nowarning');
var is_web = jinniParams.includes('--web');
var is_norun = jinniParams.includes('--norun');
var is_nocompile = jinniParams.includes('--nocompile');

ErrorManager.showWarnings = !is_nowarning;

if (!mainFilePath.endsWith('.جني')) {
	console.error('يرجا ئعطائ ملف جني');
	process.exit();
}

const projectPath = path.resolve(path.dirname(mainFilePath));
const fileName = path.basename(mainFilePath, '.جني');
const outPath = path.join(projectPath, '__خام__');

if (is_nocompile) {
	return runScript();
}


// remove then create bin folder
try {
	fs.rmSync(outPath, { recursive: true });
} catch (err) {
} finally {
	fs.mkdirSync(outPath);
}

// compile the given main script file
let code;
try {
	const data = fs.readFileSync(mainFilePath, 'utf8');
	code = data;
} catch (error) {
	console.error('فشلت قرائة الملف: ', error);
}

try {
	const parser = createParser();
	const result = parser.parse(code, {
		filePath: mainFilePath,
		projectPath: projectPath,
		outPath: outPath
	});
} catch (error) {
	let projectBasePath = path.dirname(projectPath);
	console.error("ملف: " + mainFilePath.replace(projectBasePath, ''));
	console.error(error);
}

// compile worker module
var workerFilePath = path.join(projectPath, 'مشتغلات.جني');
try {
	code = fs.readFileSync(workerFilePath, 'utf8');
} catch (error) {
	code = "";
}

try {
	const parser = createParser();
	const result = parser.parse(code, {
		filePath: workerFilePath,
		projectPath: projectPath,
		outPath: outPath
	});
} catch (error) {
	let projectBasePath = path.dirname(projectPath);
	console.error("ملف: " + workerFilePath.replace(projectBasePath, ''));
	console.error(error);
}

ErrorManager.printAll(false);

if (ErrorManager.isBlocking) {
	console.error('خطئين فادحين، ترجا المراجعة');
	process.exit();
}

// generate files
if (is_web) {
	// template index.html
	var indexhtml;
	try {
		indexhtml = fs.readFileSync(path.join(__dirname, './templates/index.html'), 'utf8');
	} catch (error) {
		console.error('فشلت قرائة الملف: ', error);
	}
	// template server.mjs
	var serverjs;
	try {
		serverjs = fs.readFileSync(path.join(__dirname, './templates/server.mjs'), 'utf8');
	} catch (error) {
		console.error('فشلت قرائة الملف: ', error);
	}
	
	
	// template package.json
	var packagejson;
	try {
		packagejson = fs.readFileSync(path.join(__dirname, './templates/package.json'), 'utf8');
	} catch (error) {
		console.error('فشلت قرائة الملف: ', error);
	}

	// process and create index.html
	indexhtml = indexhtml.replace('%ئسملف%', fileName);
	try {
		fs.writeFileSync(path.join(projectPath, 'index.html'), indexhtml, { flag: 'w+' });
	} catch (error) {
		console.error('فشلت الكتابة في الملف: ', error);
	}
	
	// run jiss
	(async function runJiss() {
		try {
			const { stdout, stderr } = await execPromise('jinni --nowarnings --nocompile ~/.jinni/jiss ' + path.join(projectPath));
			if (stderr) {
				console.error(stderr);
			}
			console.log(stdout);
		} catch (error) {
			console.error(error.message);
		}
	})();
	
	// process and create server.mjs
	try {
		fs.writeFileSync(path.join(projectPath, 'server.mjs'), serverjs, { flag: 'w+' });
	} catch (error) {
		console.error('فشلت الكتابة في الملف: ', error);
	}
	
	// process and create package.json
	var deps = {};
	ImportManager.dependencies.forEach(d => {
		deps[d] = 'latest';
	});
	packagejson = packagejson.replace('%ئعتمادين%', JSON.stringify(deps));
	try {
		fs.writeFileSync(path.join(projectPath, 'package.json'), packagejson, { flag: 'w+' });
	} catch (error) {
		console.error('فشلت الكتابة في الملف: ', error);
	}
	
	// run server
	runScript(path.join(projectPath, 'server.mjs'));
} else {
	// run
	runScript(path.join(projectPath, '__خام__', fileName + '.mjs ') + userParams.join(' '));
}

async function runScript(myscript) {
	if (!is_norun) {
		try {
			const { stdout, stderr } = await execPromise('node ' + myscript);
			if (stderr) {
				console.error(stderr);
			}
			console.log(stdout);
		} catch (error) {
			console.error(error.message);
		}
	}
}
